#!/bin/sh
# 2011-03-17, Created by H Fuchs <hagen.fuchs@physik.tu-dresden.de>
#
# Purpose: My all-purpose, snapshoting backup script.
# Backup / - exceptions are defined in /etc/foxup/ignore.
#
# TODO Hourly backups (indeed, any interval)!

port=874
server="localhost"
localhost=`hostname`

PATH="/bin:/usr/bin"

# Load defaults (server name, logger definitions, ...).
. /etc/default/foxup

# Now set the final option blob.
# TODO In /etc/default?
rsync_options="--port=$port --delete --archive --hard-links --acls \
    --xattrs --exclude-from /etc/foxup/ignore --link-dest=../day.1"

# Run pre-backup scripts now.
run-parts --exit-on-error --report /etc/foxup/pre_backup.d

# Note: Backing up the *whole* fs tree!  Edit your filter file!
$log_info "Starting the backup."
rsync $rsync_options / $server::$localhost/day.0

# Let the world know.
if [ "$?" = "0" ]; then
    $log_info "Backup successful."; exit 0
else
    $log_err "Backup failed (error $?)."; exit 3
fi

# TODO post-backup scripts?

