#!/bin/sh
# 2011-03-17, Created by H Fuchs <hagen.fuchs@physik.tu-dresden.de>
#
# Purpose: My all-purpose, snapshoting backup script.
# Backup / - exceptions are defined in /etc/foxup/ignore.
#
# TODO Hourly backups (indeed, any interval)!

PATH="/bin:/usr/bin"

# Parameters -- to be overriden in /etc/default/foxup-client.
run=no
server="localhost"
port=874
log_info="logger -i -t foxup-client -p daemon.info"
log_err="logger -s -i -t foxup-client -p daemon.err"
client=$(hostname)

# Load defaults (server name, logger definitions, ...).
. /etc/default/foxup

# Go?
if [ "$run" != "yes" ]; then
    $log_info "Not starting any backups (see /etc/default/foxup-client)."
    exit 0  # It's a perfectly expected way to quit.
fi

# Now set the final option blob.  TODO In /etc/default?
rsync_options="--port=$port --delete --archive --hard-links --acls \
    --xattrs --exclude-from /etc/foxup/ignore --link-dest=../day.1"

# Run pre-backup scripts now.
run-parts --exit-on-error --report /etc/foxup/pre_backup.d

# Note: Backing up the *whole* fs tree!  Edit your filter file!
$log_info "Starting the backup."
rsync $rsync_options / $server::$client/day.0

# Let the world know.
if [ "$?" = "0" ]; then
    $log_info "Backup successful."; exit 0
else
    $log_err "Backup failed (error $?)."; exit 3
fi

# TODO post-backup scripts?

